Catch failure in script, restart if it fails

diff --git a/userpatches/overlay/rebuild-first-run/rebuild-first-run b/userpatches/overlay/rebuild-first-run/rebuild-first-run
--- a/userpatches/overlay/rebuild-first-run/rebuild-first-run
+++ b/userpatches/overlay/rebuild-first-run/rebuild-first-run
@@ -10,6 +10,11 @@ echo "Starting rebuild first run script"
 echo "--Beginning of first run script--" > /var/log.hdd/rebuild-first-run.log
 
 HARDWARE_REVISION=$(get-recore-revision)
+if [ "${HARDWARE_REVISION}" != @(a5|a6|a7|a8) ]; then
+    log "Error getting hardware revision"
+    exit 1
+fi
+
 log "Found Recore hardware revision ${HARDWARE_REVISION}"
 if [ "${HARDWARE_REVISION}" == "a8" ]; then
     log "Starting and enabling usb-role-switch.timer"
